trigger:
  branches:
    include:
      - master

variables:
  imageTag: "$(Build.BuildId)" # Using The Build ID as Tag
  environment: "dev" 

stages:
  - stage: "DEV"
    displayName: "Deploy to DEV"
    jobs:
      - job: "CreateInfra"
        displayName: "Creating Infrastructure"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - template: template/infra.yaml
      - job: "BuildAndPushDockerImage"
        dependsOn: "CreateInfra"
        displayName: "Build-Push DockerImage"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - template: template/docker.yaml
      - job: "ConatineApp" #Deploying ContainerApp
        dependsOn: "BuildAndPushDockerImage" 
        steps:
          - template: template/containerapp.yaml
